services:
  # Service pour PHP avec Symfony
  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ./app:/var/www/html
    networks:
      - symfony_network
    depends_on:
      - db

  # Service pour la base de données (PostgreSQL ici)
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/datas
    networks:
      - symfony_network

  # Service pour le serveur Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - symfony_network

  # Service pour pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - symfony_network

volumes:
  db_data:


networks:
  symfony_network:
    driver: bridge
