services:
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony
      - nextjs-app
    networks:
      - app-network

  symfony:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony-back
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

    environment:
      APP_ENV: dev
      APP_SECRET: your_app_secret
      DATABASE_URL: "mysql://root:root_password@mariadb/db_name"

  nextjs-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs-front
    networks:
      - app-network
    environment:
      NODE_ENV: production

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_password
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "81:80"
    depends_on:
      - mariadb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data:
