security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
      dev:
        pattern: ^/_(profiler|wdt)
        security: true
      main:
        stateless: true
        provider: app_user_provider
        json_login:
            check_path: /auth
            username_path: email
            password_path: password
            success_handler: App\Controller\ApiLoginController
            failure_handler: lexik_jwt_authentication.handler.authentication_failure
        jwt: ~

    access_control:
    - { path: ^/$, roles: PUBLIC_ACCESS }
    - { path: ^/docs, roles: ROLE_USER }
    - { path: ^/auth, roles: PUBLIC_ACCESS }
    - { path: ^/users/verify-email, roles: PUBLIC_ACCESS }
    - {path: ^/events, roles: ROLE_USER}
    
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
