Table "doctrine_migration_versions" {
  "version" varchar(191) [pk, not null]
  "executed_at" timestamp [default: `NULL::timestamp without time zone`]
  "execution_time" int4
}

Table "greeting" {
  "id" int4 [pk, not null]
  "name" varchar(255) [not null]
}

Table "user" {
  "id" int4 [pk, not null]
  "email" varchar(180) [unique, not null]
  "roles" json [not null]
  "password" varchar(255) [not null]
  "firstname" varchar(255) [not null]
  "lastname" varchar(255) [not null]
  "username" varchar(255) [unique, not null]
  "photo" varchar(255) [not null]
  "emailverify" bool [not null]
  "emaillink" varchar(255) [not null]
  "tokenpassword" text
}

Table "event" {
  "id" int4 [pk, not null]
  "title" varchar(255) [not null]
  "description" text [not null]
  "datestart" timestamp [not null]
  "dateend" timestamp [not null]
  "location" text [not null]
  "visibility" bool [not null]
  "sharelink" varchar(255) [not null]
  "maxparticipant" int8 [not null]
  "img" varchar(255) [not null]
  "deleted_date" timestamp [default: `NULL::timestamp without time zone`]
}

Table "user_event" {
  "id" int4 [pk, not null]
  "event_id" int4 [not null]
  "user_id" int4
  "role" varchar(255) [not null]
  "user_email" varchar(255)

  Indexes {
    event_id [type: btree, name: "idx_d96cf1ff71f7e88b"]
    user_id [type: btree, name: "idx_d96cf1ffa76ed395"]
  }
}

Table "user_invitation" {
  "id" int4 [pk, not null]
  "event_id" int4 [not null]
  "email" varchar(255) [not null]
  "link" varchar(255) [not null]
  "expiration" timestamp [not null]

  Indexes {
    event_id [type: btree, name: "idx_567aa74e71f7e88b"]
  }
}

Ref "fk_d96cf1ff71f7e88b":"event"."id" < "user_event"."event_id"

Ref "fk_d96cf1ffa76ed395":"user"."id" < "user_event"."user_id" [delete: set null]

Ref "fk_567aa74e71f7e88b":"event"."id" < "user_invitation"."event_id"
